import 'package:uuid/uuid.dart';

/// UUID generation — design.md §10.
///
/// Pure Dart (package:uuid has no Flutter dependency), so `core/` stays
/// testable without a device.
const Uuid _uuid = Uuid();

/// A fresh UUIDv4, used for message ids and transfer ids.
///
/// Random rather than sequential on purpose: a `msgId` is generated by the
/// *sender* and is the key the receiver dedupes on (design.md §4.5), so it has
/// to be unique across every device on the LAN without any coordination.
String newId() => _uuid.v4();
