/// A chat message — design.md §5.1 `message` table.
///
/// Pure Dart, no Flutter import, so the ordering and status rules below are
/// unit-testable without a device.
class Message {
  const Message({
    required this.id,
    required this.peerId,
    required this.direction,
    required this.type,
    required this.status,
    required this.createdAt,
    this.text,
    this.deliveredAt,
    this.retryCount = 0,
  });

  /// Globally unique, generated by the sender (design.md §4.5).
  ///
  /// Re-sends deliberately reuse it — that is what lets the receiver drop a
  /// duplicate instead of showing the message twice.
  final String id;

  /// The other party. A v1 conversation is one-to-one, so this is also the
  /// conversation's identity: `conversation.id == conversation.peer_id`.
  final String peerId;

  final MessageDirection direction;
  final MessageType type;

  /// Body text. Null for message types whose content is an attachment.
  final String? text;

  final MessageStatus status;

  /// When this device stored the message — never the peer's clock (design.md
  /// §4.5). Two machines on a LAN routinely disagree about the time, and
  /// sorting by a remote clock makes the history rearrange itself.
  final DateTime createdAt;

  final DateTime? deliveredAt;

  /// How many times this has been re-sent. Capped by `kMsgMaxRetries`.
  final int retryCount;

  bool get isOutgoing => direction == MessageDirection.outgoing;

  /// Whether the send has finished, successfully or not. Anything else is
  /// still owed an attempt, and is what the offline queue re-sends (§5.2).
  bool get isSettled =>
      status == MessageStatus.delivered ||
      status == MessageStatus.received ||
      status == MessageStatus.failed;

  /// Whether the UI should offer a retry.
  bool get canRetry => status == MessageStatus.failed;

  Message copyWith({
    MessageStatus? status,
    DateTime? deliveredAt,
    int? retryCount,
    String? text,
  }) {
    return Message(
      id: id,
      peerId: peerId,
      direction: direction,
      type: type,
      text: text ?? this.text,
      status: status ?? this.status,
      createdAt: createdAt,
      deliveredAt: deliveredAt ?? this.deliveredAt,
      retryCount: retryCount ?? this.retryCount,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is Message &&
      other.id == id &&
      other.peerId == peerId &&
      other.direction == direction &&
      other.type == type &&
      other.text == text &&
      other.status == status &&
      other.createdAt == createdAt &&
      other.deliveredAt == deliveredAt &&
      other.retryCount == retryCount;

  @override
  int get hashCode => Object.hash(
    id,
    peerId,
    direction,
    type,
    text,
    status,
    createdAt,
    deliveredAt,
    retryCount,
  );

  @override
  String toString() => 'Message($id, $direction, $type, $status)';

  /// Oldest first — the canonical order, and the order the chat is read in.
  ///
  /// Ties are broken by id, which matters more than it looks: two messages can
  /// share a `created_at` millisecond (a burst of queued messages flushed after
  /// a reconnect all get stored in the same tick), and a comparator that
  /// returned 0 for them would let the list order differ between two runs of
  /// the same data. Ids are UUIDv4, so the tiebreak is arbitrary but *stable*,
  /// which is all a display order needs (design.md §4.5).
  static int compareOldestFirst(Message a, Message b) {
    final int byTime = a.createdAt.compareTo(b.createdAt);
    if (byTime != 0) {
      return byTime;
    }
    return a.id.compareTo(b.id);
  }

  /// Newest first — exactly the reverse of [compareOldestFirst].
  ///
  /// This is the order the database returns (design.md §4.5) and the order a
  /// reverse-scrolling list consumes. Defined as the reverse rather than as its
  /// own `(time DESC, id ASC)` so that the two orders can never contradict each
  /// other: sorting a page and reversing it must give the same sequence.
  static int compareNewestFirst(Message a, Message b) =>
      compareOldestFirst(b, a);
}

/// Which way a message travelled. Stored as `'in'` / `'out'`.
enum MessageDirection {
  incoming('in'),
  outgoing('out');

  const MessageDirection(this.wire);

  final String wire;

  static MessageDirection fromWire(String value) {
    return MessageDirection.values.firstWhere(
      (MessageDirection d) => d.wire == value,
      orElse: () => MessageDirection.incoming,
    );
  }
}

/// What a message carries — design.md §5.1.
///
/// `image` is kept apart from `file` because it renders as a picture rather
/// than a card, and `system` covers local notices ("file deleted") that were
/// never on the wire.
enum MessageType {
  text('text'),
  file('file'),
  image('image'),
  folder('folder'),
  system('system');

  const MessageType(this.wire);

  final String wire;

  static MessageType fromWire(String value) {
    return MessageType.values.firstWhere(
      (MessageType t) => t.wire == value,
      orElse: () => MessageType.text,
    );
  }
}

/// Where a message is in its journey — design.md §4.5.
///
/// The order below is the order of the outgoing state machine:
/// `pending` → `sent` → `delivered`.
enum MessageStatus {
  /// Written locally, not yet acknowledged as sent. Covers both "queued
  /// because the peer is offline" and "sent, awaiting ack".
  pending('pending'),

  /// On the wire, no ack yet.
  sent('sent'),

  /// The peer confirmed it stored the message.
  delivered('delivered'),

  /// Retries exhausted, or the peer rejected it. The UI offers a retry.
  failed('failed'),

  /// Stored from an incoming frame. Terminal — nothing acknowledges an ack.
  received('received');

  const MessageStatus(this.wire);

  final String wire;

  static MessageStatus fromWire(String value) {
    return MessageStatus.values.firstWhere(
      (MessageStatus s) => s.wire == value,
      orElse: () => MessageStatus.pending,
    );
  }
}
